### ISSUE TITLE
[Data browser] Number type input can't be empty string

### ISSUE THREAD

**Issue by WatanabeToshimitsu** [dataware-tools/dataware-tools#100]
## Purpose
Bug report

## Description
Number type input can't be empty string.

```
INFO:     127.0.0.6:52205 - "POST /databases/test-v011/records HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 216, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 151, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/app/api/records.py", line 121, in create_record
    resp = _create_record(escape_string(database_id, kind='id'), data)
  File "/opt/app/api/records.py", line 343, in _create_record
    handler.add_data(info)
  File "/usr/local/lib/python3.8/site-packages/pydtk/db/v4/handlers/meta.py", line 194, in add_data
    super().add_data(data_to_store, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pydtk/db/v4/handlers/__init__.py", line 562, in add_data
    _fix_data_type(data, columns, inplace=True)
  File "/usr/local/lib/python3.8/site-packages/pydtk/db/v4/handlers/__init__.py", line 97, in _fix_data_type
    data[key] = float(data[key])
ValueError: could not convert string to float: ''
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 216, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 151, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/app/api/records.py", line 121, in create_record
    resp = _create_record(escape_string(database_id, kind='id'), data)
  File "/opt/app/api/records.py", line 343, in _create_record
    handler.add_data(info)
  File "/usr/local/lib/python3.8/site-packages/pydtk/db/v4/handlers/meta.py", line 194, in add_data
    super().add_data(data_to_store, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pydtk/db/v4/handlers/__init__.py", line 562, in add_data
    _fix_data_type(data, columns, inplace=True)
  File "/usr/local/lib/python3.8/site-packages/pydtk/db/v4/handlers/__init__.py", line 97, in _fix_data_type
    data[key] = float(data[key])
ValueError: could not convert string to float: ''
```

## Screenshot or video
![NumberTypeBug](https://user-images.githubusercontent.com/72174933/147446318-6b968a92-4c8c-4391-ac44-e45effe0fd0b.gif)

**Comment by d-hayashi** [comment]
バックエンド側で空文字だったらNoneにする

**Comment by d-hayashi** [comment]
`pydtk >= 0.1.10` で解決されているので api-meta-store で `pydtk >= 0.1.10` を使う様に変更します
